alias resource="source ~/.profile"
alias wslconfig="vim /mnt/c/Users/mitchelj/.wslconfig"
alias vim="nvim"
alias myvimrc="nvim ~/.config/nvim/init.lua"
alias downloads="cd /mnt/c/Users/mitchelj/Downloads"
alias up="docker compose up -d"
alias down="docker compose down"
alias cat="batcat"
alias sonnet="ANTHROPIC_MODEL='us.anthropic.claude-3-7-sonnet-20250219-v1:0' claude"
alias haiku="ANTHROPIC_MODEL='us.anthropic.claude-3-5-haiku-20241022-v1:0' claude"
alias hq="harlequin"
alias clauded="claude --dangerously-skip-permissions"
