# This viminfo file was generated by Vim 8.2.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/erm

# Last Substitute Search Pattern:
~MSle0&erm

# Last Substitute String:
$

# Command Line History (newest to oldest):
:wq
|2,0,1652727802,,"wq"
:w
|2,0,1652675518,,"w"
:term
|2,0,1652675337,,"term"
:q
|2,0,1652293317,,"q"
:e sstring.h
|2,0,1652275528,,"e sstring.h"
:set shiftwidth=2
|2,0,1652275415,,"set shiftwidth=2"
:set tabstop=2
|2,0,1652275408,,"set tabstop=2"
:set expandtab
|2,0,1652275397,,"set expandtab"
:set shiftwidth=4
|2,0,1652275392,,"set shiftwidth=4"
:set tabstop=4
|2,0,1652275385,,"set tabstop=4"
:q!
|2,0,1652076281,,"q!"
:WQ
|2,0,1652076275,,"WQ"
:e poly.h
|2,0,1651674766,,"e poly.h"
:v
|2,0,1651674761,,"v"
:v term
|2,0,1651673658,,"v term"
:vterm
|2,0,1651673655,,"vterm"
:term v
|2,0,1651673650,,"term v"
:e poly.c
|2,0,1651644396,,"e poly.c"
:e main.c
|2,0,1651640739,,"e main.c"
:wo
|2,0,1651640290,,"wo"
:W
|2,0,1651639946,,"W"
:wa;
|2,0,1651639384,,"wa;"
:e
|2,0,1651250680,,"e"
:e ed.cpp
|2,0,1651076472,,"e ed.cpp"
:e t2
|2,0,1651075751,,"e t2"
:e words.h
|2,0,1651075653,,"e words.h"
:e line.h
|2,0,1651075615,,"e line.h"
:%s/to_string/std::to_string
|2,0,1651075479,,"%s/to_string/std::to_string"
:e word.h
|2,0,1651073692,,"e word.h"
:e t1
|2,0,1651069797,,"e t1"
:e doc.h
|2,0,1651069443,,"e doc.h"
:e line.cpp
|2,0,1651067717,,"e line.cpp"
:!dir
|2,0,1651066367,,"!dir"
:dir!
|2,0,1651066365,,"dir!"
:Wq
|2,0,1650817606,,"Wq"
:e ~\vimfiles\templates\skeleton.cpp
|2,0,1650816295,,"e ~\\vimfiles\\templates\\skeleton.cpp"
:w!
|2,0,1650752869,,"w!"
:e ~/vimfiles/templates.vim
|2,0,1650733999,,"e ~/vimfiles/templates.vim"
:e $MYVIMRC
|2,0,1650733987,,"e $MYVIMRC"
:e map.cpp
|2,0,1650603166,,"e map.cpp"
:e map.h
|2,0,1650597064,,"e map.h"
:CocInfo
|2,0,1650595280,,"CocInfo"
:version
|2,0,1650595261,,"version"
:PlugInstall
|2,0,1650595180,,"PlugInstall"
:echo $HOME
|2,0,1650594272,,"echo $HOME"
:e ..\plugin.vim
|2,0,1650594045,,"e ..\\plugin.vim"
:e $VIMRUNTIME/vimrc_example.vim
|2,0,1650593516,,"e $VIMRUNTIME/vimrc_example.vim"
:!pwd
|2,0,1650592460,,"!pwd"
:.!pwd
|2,0,1650592445,,".!pwd"
:pwd
|2,0,1650592423,,"pwd"
:echo %TMP%
|2,0,1650592420,,"echo %TMP%"
:wq!
|2,0,1650592391,,"wq!"
:echo ~
|2,0,1650592243,,"echo ~"
:e ~
|2,0,1650591285,,"e ~"
:verbose set backupdir
|2,0,1650590603,,"verbose set backupdir"
:!
|2,0,1650589325,,"!"
:he backup
|2,0,1650589270,,"he backup"
:e ~/vimfiles/setup.vim
|2,0,1650574448,,"e ~/vimfiles/setup.vim"
:e vector.cpp
|2,0,1650573749,,"e vector.cpp"
:e vector.h
|2,0,1650573364,,"e vector.h"
:%s/endl/std::endl/gc
|2,0,1650331510,,"%s/endl/std::endl/gc"
:w constTest.cpp
|2,0,1650331417,,"w constTest.cpp"
:'<,'>wq
|2,0,1650308594,,"'<,'>wq"
:%s/map/cur_map/gc
|2,0,1649219161,,"%s/map/cur_map/gc"
:e robot.h
|2,0,1649219097,,"e robot.h"
:e robot.cpp
|2,0,1649218346,,"e robot.cpp"
:e cell.cpp
|2,0,1649218010,,"e cell.cpp"
:e cell.h
|2,0,1649217761,,"e cell.h"
:%s/"/'/gc
|2,0,1649214414,,"%s/\"/'/gc"
:%s/Chicken/Pig/gc
|2,0,1649082918,,"%s/Chicken/Pig/gc"
:w hw5.cpp
|2,0,1649082072,,"w hw5.cpp"
:%s/int/ll/gc
|2,0,1648927640,,"%s/int/ll/gc"
:qw
|2,0,1648927115,,"qw"
:exit
|2,0,1648934778,,"exit"
:%s/minimum/cur_path/gc
|2,0,1648913801,,"%s/minimum/cur_path/gc"
:%s/1e6/val/gc
|2,0,1648874733,,"%s/1e6/val/gc"
:e bs.rb
|2,0,1646834964,,"e bs.rb"
:e ~/vimfiles/templates/skeleton.cpp
|2,0,1646280823,,"e ~/vimfiles/templates/skeleton.cpp"
:e ~/vimfiles/mapping.vim
|2,0,1646280550,,"e ~/vimfiles/mapping.vim"
:l
|2,0,1645159096,,"l"
:w "eyeofsauran"
|2,0,1643414451,,"w \"eyeofsauran\""
:%s/ //g
|2,0,1642144429,,"%s/ //g"
:%s/ /
|2,0,1642144416,,"%s/ /"
:%s/ /"\n"/g
|2,0,1642144407,,"%s/ /\"\\n\"/g"
:%s/ /\n/g
|2,0,1642144383,,"%s/ /\\n/g"
:!q
|2,0,1642144360,,"!q"
:%s/FC_PU/F_CPU/g
|2,0,1642142387,,"%s/FC_PU/F_CPU/g"
:set list
|2,0,1639373199,,"set list"
:e dayxx.cpp
|2,0,1638740916,,"e dayxx.cpp"
:e :wq
|2,0,1637340234,,"e :wq"
:w'
|2,0,1635540648,,"w'"
:w:w
|2,0,1632490917,,"w:w"
:dir
|2,0,1631222850,,"dir"
:w! test.sh
|2,0,1631220733,,"w! test.sh"
:w test.sh
|2,0,1631220728,,"w test.sh"
:test.sh
|2,0,1631220611,,"test.sh"
:%s/paint(/paint(-1,/gc
|2,0,1630948199,,"%s/paint(/paint(-1,/gc"
:%s/'/"/gc
|2,0,1630946092,,"%s/'/\"/gc"
:wkkkkkkk
|2,0,1629669115,,"wkkkkkkk"
:s
|2,0,1628961518,,"s"
:%s/last/cur
|2,0,1628963922,,"%s/last/cur"
:%s/leftRotate/ROTL/
|2,0,1628882354,,"%s/leftRotate/ROTL/"
:%s/rightRotate/ROTR/
|2,0,1628882322,,"%s/rightRotate/ROTR/"
:%s/ll/long int
|2,0,1628881829,,"%s/ll/long int"
:wk
|2,0,1628878972,,"wk"
:e alamode.cpp
|2,0,1628874568,,"e alamode.cpp"
:ww
|2,0,1628873131,,"ww"
::q
|2,0,1628867683,,":q"
:PluginInstall
|2,0,1628867384,,"PluginInstall"
:w:wq
|2,0,1628866335,,"w:wq"
:make
|2,0,1628864212,,"make"
:map!
|2,0,1628831580,,"map!"
:map
|2,0,1628831573,,"map"
:wjjjjjjjjjjjjj
|2,0,1628830292,,"wjjjjjjjjjjjjj"
:wqk
|2,0,1628786492,,"wqk"
:!echo $MYVIMRC
|2,0,1628695584,,"!echo $MYVIMRC"
:e Mating.cpp
|2,0,1628612970,,"e Mating.cpp"
:e Mating2.cpp
|2,0,1628611603,,"e Mating2.cpp"
:split
|2,0,1628611543,,"split"
:vi
|2,0,1628611531,,"vi"
:V
|2,0,1628611526,,"V"
:h
|2,0,1628611522,,"h"
:e inahoviii.cpp
|2,0,1628548941,,"e inahoviii.cpp"
: inahoviii.cpp
|2,0,1628548930,," inahoviii.cpp"
:s/sum/product
|2,0,1628521052,,"s/sum/product"
:x
|2,0,1628508667,,"x"
:%s/to/next/gc
|2,0,1627350481,,"%s/to/next/gc"
:%s/to/next/g
|2,0,1627350357,,"%s/to/next/g"
:%s/trie/node/gc
|2,0,1627349932,,"%s/trie/node/gc"
:e .profile.txt
|2,0,1626921664,,"e .profile.txt"
:%s/&&/and/g
|2,0,1626308231,,"%s/&&/and/g"
:c
|2,0,1626306233,,"c"
:%s/i/_i/gc
|2,0,1625863674,,"%s/i/_i/gc"
:%s/->/./gc
|2,0,1625785944,,"%s/->/./gc"
:s/->/./gc
|2,0,1625785928,,"s/->/./gc"
:w | !cls && g++ % 
|2,0,1625188009,,"w | !cls && g++ % "
:splitv
|2,0,1625180567,,"splitv"
:!(g++ squawk.cpp)
|2,0,1625179142,,"!(g++ squawk.cpp)"
:%s/output += /cout<</gc
|2,0,1625010766,,"%s/output += /cout<</gc"
:%s/left/right/gc
|2,0,1625010109,,"%s/left/right/gc"
:s/left/right/gc
|2,0,1625010101,,"s/left/right/gc"
:s/left/right
|2,0,1625009968,,"s/left/right"
:%s/left
|2,0,1625009933,,"%s/left"
:s/left
|2,0,1625009920,,"s/left"
:%s/step/l/
|2,0,1624401265,,"%s/step/l/"

# Search String History (newest to oldest):
?/vga_r
|2,1,1652198203,47,"vga_r"
? @$
|2,1,1651766324,,"@$"
? erm
|2,1,1651673658,,"erm"
?/MAXLEN
|2,1,1651644370,47,"MAXLEN"
?/maxlen
|2,1,1651644366,47,"maxlen"
? ^\(\s*\)\/\/\/\/
|2,1,1651643001,,"^\\(\\s*\\)\\/\\/\\/\\/"
?/vga_sync
|2,1,1651613824,47,"vga_sync"
?/fp
|2,1,1651613537,47,"fp"
?/i2c
|2,1,1651613223,47,"i2c"
?/address
|2,1,1651613176,47,"address"
?/base
|2,1,1651516546,47,"base"
?/baseImage
|2,1,1651516453,47,"baseImage"
?/load
|2,1,1651514710,47,"load"
?/clear
|2,1,1651164305,47,"clear"
?/containsKey
|2,1,1651164254,47,"containsKey"
?/values
|2,1,1651164160,47,"values"
?/ketSet
|2,1,1651164155,47,"ketSet"
?/chainEntry
|2,1,1651163174,47,"chainEntry"
?/get
|2,1,1651162284,47,"get"
?/hashmapIndex
|2,1,1651162139,47,"hashmapIndex"
?/Word
|2,1,1651076040,47,"Word"
? to_string
|2,1,1651075479,,"to_string"
?//
|2,1,1651074984,47,"/"
?/range
|2,1,1651074649,47,"range"
?/range_err
|2,1,1651074514,47,"range_err"
?/word
|2,1,1651073558,47,"word"
?/size
|2,1,1651069742,47,"size"
?/p
|2,1,1651069603,47,"p"
?/p 
|2,1,1651069599,47,"p "
?/cout
|2,1,1651068441,47,"cout"
?/reg
|2,1,1650934645,47,"reg"
? endl
|2,1,1650331510,,"endl"
?/int
|2,1,1649471633,47,"int"
?/Robot
|2,1,1649255849,47,"Robot"
?/robot
|2,1,1649255841,47,"robot"
? map
|2,1,1649219161,,"map"
? "
|2,1,1649214414,,"\""
? Chicken
|2,1,1649082918,,"Chicken"
?/K
|2,1,1648937893,47,"K"
?/K 
|2,1,1648937812,47,"K "
?/8000
|2,1,1648937744,47,"8000"
? int
|2,1,1648927640,,"int"
? minimum
|2,1,1648913801,,"minimum"
? 1e6
|2,1,1648874733,,"1e6"
?  
|2,1,1642144429,," "
? FC_PU
|2,1,1642142387,,"FC_PU"
?/FC_PU
|2,1,1642142347,47,"FC_PU"
? paint(
|2,1,1630948199,,"paint("
? \<cout\>
|2,1,1630947564,,"\\<cout\\>"
?// var types
|2,1,1630947564,47,"/ var types"
?/case
|2,1,1630946905,47,"case"
? '
|2,1,1630946092,,"'"
?/pq
|2,1,1628966864,47,"pq"
? last
|2,1,1628963922,,"last"
? leftRotate
|2,1,1628882354,,"leftRotate"
? rightRotate
|2,1,1628882322,,"rightRotate"
? ll
|2,1,1628881829,,"ll"
? sum
|2,1,1628826544,,"sum"
?/`
|2,1,1628479879,47,"`"
?/rolls
|2,1,1628476887,47,"rolls"
?/trie
|2,1,1627350502,47,"trie"
? to
|2,1,1627350481,,"to"
? trie
|2,1,1627349932,,"trie"
? &&
|2,1,1626308231,,"&&"
? i
|2,1,1625863674,,"i"
? ->
|2,1,1625785944,,"->"
? output += 
|2,1,1625010766,,"output += "
? left
|2,1,1625010109,,"left"
?/left
|2,1,1625009951,47,"left"
?/s/left
|2,1,1625009945,47,"s/left"
? step
|2,1,1624401265,,"step"
? ;
|2,1,1623816804,,";"
? data
|2,1,1623562664,,"data"
? client
|2,1,1623466262,,"client"
? junc
|2,1,1623466085,,"junc"
? count
|2,1,1622087084,,"count"
?// of a Roman symbol
|2,1,1622345836,47,"/ of a Roman symbol"
?// This function returns value
|2,1,1622345836,47,"/ This function returns value"
? Edge
|2,1,1622001161,,"Edge"
? edge
|2,1,1622001140,,"edge"
? /Edge/Segment/
|2,1,1622001133,,"/Edge/Segment/"
? dfs
|2,1,1621527570,,"dfs"
? double
|2,1,1620500660,,"double"
? not
|2,1,1619868136,,"not"
? nn
|2,1,1619211773,,"nn"
?/%/nn/endl
|2,1,1619211734,47,"%/nn/endl"
?/fast
|2,1,1619050782,47,"fast"
?/fash
|2,1,1619050780,47,"fash"
?/toStr
|2,1,1618323048,47,"toStr"
?/toSt
|2,1,1618323011,47,"toSt"
?/toString
|2,1,1618322978,47,"toString"
?//dfs
|2,1,1615309379,47,"/dfs"
? ,
|2,1,1614796286,,","
? \<x\>
|2,1,1602105834,,"\\<x\\>"
? \s\+$
|2,1,1596226727,,"\\s\\+$"
?/j
|2,1,1595860955,47,"j"
?/passcode
|2,1,1595860944,47,"passcode"
?/continue
|2,1,1595860919,47,"continue"
? \<ior\>
|2,1,1591732193,,"\\<ior\\>"
?/id
|2,1,1554168480,47,"id"
? \<with\>
|2,1,1550708454,,"\\<with\\>"

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@:q
|2,3,1639168394,,":q"

# Debug Line History (newest to oldest):

# Registers:
""0	LINE	0
	    cout<<s[1]<<endl;
|3,1,0,1,1,0,1652675517,"    cout<<s[1]<<endl;"
"1	LINE	0
	
|3,0,1,1,1,0,1652675437,""
"2	LINE	0
		int date = 10*(0x3&(recieve[5]>>4))+0xF&(recieve[5]);
|3,0,2,1,1,0,1652557513,"	int date = 10*(0x3&(recieve[5]>>4))+0xF&(recieve[5]);"
"3	LINE	0
	    // FIXME: write character i from the src's text
|3,0,3,1,1,0,1652275807,"    // FIXME: write character i from the src's text"
"4	LINE	0
	  // FIXME: implement this
|3,0,4,1,1,0,1652275805,"  // FIXME: implement this"
"5	LINE	0
	  //   4. return the pointer
|3,0,5,1,1,0,1652275801,"  //   4. return the pointer"
"6	LINE	0
	  //   3. copy len characters from src to the String10 value
|3,0,6,1,1,0,1652275800,"  //   3. copy len characters from src to the String10 value"
"7	LINE	0
	  //      up to 10 characters
|3,0,7,1,1,0,1652275799,"  //      up to 10 characters"
"8	LINE	0
	  //   2. set the len field to the number of characters in the source
|3,0,8,1,1,0,1652275799,"  //   2. set the len field to the number of characters in the source"
"9	LINE	0
	  //   1. allocate space on the heap using malloc
|3,0,9,1,1,0,1652275797,"  //   1. allocate space on the heap using malloc"
"w@	CHAR	0
	Icame€kb_write_register(0xlla, 0xA);j
|3,2,32,0,1,0,1652218971,"Icame€kb_write_register(0xlla, 0xA);j"
"-	CHAR	0
	 
|3,0,36,0,1,0,1652675331," "

# File marks:
'0  23  4  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Final\string5.cpp
|4,48,23,4,1652727802,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\C&C++\\Final\\string5.cpp"
'1  17  8  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\RTC.c
|4,49,17,8,1652557714,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\RTC.c"
'2  13  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,50,13,13,1652555303,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
'3  13  14  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,51,13,14,1652555277,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
'4  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,52,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
'5  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,53,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
'6  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,54,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
'7  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,55,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
'8  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,56,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
'9  54  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Winter\Computational Science\Assignments\Assignment14\fizzbuzz.sh
|4,57,54,0,1652454802,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Winter\\Computational Science\\Assignments\\Assignment14\\fizzbuzz.sh"

# Jumplist (newest first):
-'  23  4  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Final\string5.cpp
|4,39,23,4,1652727802,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\C&C++\\Final\\string5.cpp"
-'  3  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Final\string5.cpp
|4,39,3,0,1652675323,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\C&C++\\Final\\string5.cpp"
-'  17  8  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\RTC.c
|4,39,17,8,1652557714,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\RTC.c"
-'  17  8  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\RTC.c
|4,39,17,8,1652557714,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\RTC.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\RTC.c
|4,39,1,0,1652556616,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\RTC.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\RTC.c
|4,39,1,0,1652556616,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\RTC.c"
-'  13  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,13,1652555303,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  13  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,13,1652555303,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  13  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,13,1652555303,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  13  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,13,1652555303,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  13  14  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,14,1652555277,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  13  14  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,14,1652555277,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  13  14  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,14,1652555277,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  13  14  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,13,14,1652555277,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555269,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  14  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,14,0,1652555259,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
|4,39,1,0,1652555187,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\adc.py"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  8  13  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,8,13,1652555179,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"
-'  1  0  ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
|4,39,1,0,1652550243,"~\\OneDrive - Milwaukee School of Engineering\\Sophomore\\Spring\\Embedded_3\\Final\\func.c"

# History of marks within files (newest to oldest):

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Final\string5.cpp
	*	1652727801	0
	"	23	4
	^	22	30
	.	23	0
	+	10	28
	+	1	17
	+	11	21
	+	16	0
	+	14	29
	+	15	29
	+	16	0
	+	21	20
	+	2	18
	+	15	25
	+	4	19
	+	5	0
	+	22	29
	+	23	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\RTC.c
	*	1652557597	0
	"	17	8
	^	17	9
	.	17	8
	+	3	48
	+	5	1
	+	3	44
	+	7	36
	+	18	37
	+	13	20
	+	14	28
	+	18	0
	+	15	26
	+	13	32
	+	15	8
	+	6	20
	+	12	26
	+	17	8

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\adc.py
	*	1652555302	0
	"	13	13
	^	13	14
	.	13	13
	+	13	13

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Final\func.c
	*	1652550442	0
	"	8	13
	^	8	14
	.	8	13
	+	3	39
	+	8	16
	+	4	24
	+	8	25
	+	5	0
	+	8	13

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Winter\Computational Science\Assignments\Assignment14\fizzbuzz.sh
	*	1652454800	0
	"	54	0

> ~\IdeaProjects\DataStructures\lab9jones-mitchell-johnstone\src\betterImplementation\GameBoard.java
	*	1652392114	0
	"	131	0

> ~\IdeaProjects\DataStructures\lab9jones-mitchell-johnstone\src\johnstonem\GameBoard.java
	*	1652392022	0
	"	88	1

> ~\IdeaProjects\DataStructures\lab9jones-mitchell-johnstone\src\johnstonem\WordSearchCLI.java
	*	1652392005	0
	"	57	0

> C:\intelFPGA_lite\18.1\ip\altera\university_program\audio_video\video\altera_up_avalon_video_pixel_buffer_dma\hdl\altera_up_avalon_video_pixel_buffer_dma.v
	*	1652290664	0
	"	141	0

> ~\Downloads\GameBoard.java
	*	1652287204	0
	"	74	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab10\sstring.c
	*	1652276197	0
	"	9	29
	^	9	30
	.	9	29
	+	16	0
	+	11	26
	+	11	31
	+	16	0
	+	15	15
	+	16	0
	+	11	59
	+	11	51
	+	11	48
	+	16	11
	+	39	12
	+	33	28
	+	2	20
	+	11	48
	+	11	51
	+	15	0
	+	11	0
	+	12	0
	+	9	0
	+	40	0
	+	33	0
	+	9	29

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab10\sstring.h
	*	1652275633	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\test.c
	*	1652274853	0
	"	10	15
	^	1	18
	.	10	15
	+	11	9
	+	5	0
	+	6	30
	+	9	19
	+	5	1
	+	10	29
	+	9	20
	+	1	17
	+	10	15

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\test.cpp
	*	1652274688	0
	"	51	3
	.	1	0
	+	1	0

> C:\intelFPGA_lite\18.1\University_Program\Computer_Systems\DE10-Lite\DE10-CE2820\verilog\software\MS9\camera.c
	*	1652226443	0
	"	15	1
	^	77	32
	.	79	0
	+	28	31
	+	29	31
	+	30	31
	+	40	31
	+	50	31
	+	71	31
	+	76	31
	+	77	31
	+	79	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\top_level.vhd
	*	1652198214	0
	"	19	27

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\fpgaCamera.vhd
	*	1652198149	0
	"	10	0
	.	108	0
	+	108	0

> C:\Program Files\Vim\vim82\doc\eval.txt
	*	1652198144	0
	"	756	8

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\SCP\ADDRESSDECODER.vhd
	*	1652197506	0
	"	55	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\SCP\ADDRESSDECODER.bsf
	*	1652197491	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Winter\Digital Logic II\Labs\Lab09\counter.vhd
	*	1652140958	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Winter\Digital Logic II\Labs\Lab09\idecode.vhd
	*	1652140947	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Winter\Digital Logic II\Labs\Lab10\Lab10.vhd
	*	1652140924	0
	"	78	0

> ~\IdeaProjects\DataStructures\lab8jones-mitchell-johnstone\src\johnstonem\HashMap.java
	*	1652076280	0
	"	161	12
	^	216	0
	.	161	12
	+	217	35
	+	218	0
	+	216	0
	+	161	12

> ~\IdeaProjects\DataStructures\lab8jones-mitchell-johnstone\src\johnstonem\MorseEncoder.java
	*	1652047834	0
	"	17	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\ov7670_capture.vhd
	*	1651958812	0
	"	18	0

> C:\intelFPGA_lite\18.1\University_Program\Computer_Systems\DE10-Lite\DE10-CE2820\verilog\seg7.vhd
	*	1651868636	0
	"	18	2

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\SCP\irom_FPGA_template.txt
	*	1651849438	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\SCP\seg7decode_template.txt
	*	1651849395	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\my_frame_buffer_15to0.vhd
	*	1651846035	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\frame_buffer.vhd
	*	1651782883	0
	"	2	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Homework\HW9\homework8.c
	*	1651680890	0
	"	5	7
	^	5	8
	.	5	7
	+	7	2
	+	21	8
	+	18	0
	+	21	0
	+	20	9
	+	18	36
	+	19	0
	+	18	0
	+	24	16
	+	25	0
	+	18	2
	+	1	12
	+	17	18
	+	17	10
	+	17	12
	+	17	22
	+	17	16
	+	24	0
	+	24	19
	+	24	0
	+	24	18
	+	24	19
	+	24	20
	+	24	19
	+	24	18
	+	24	0
	+	17	0
	+	23	21
	+	3	21
	+	18	1
	+	24	18
	+	24	14
	+	24	12
	+	24	0
	+	17	2
	+	18	36
	+	17	11
	+	18	36
	+	17	0
	+	5	0
	+	10	1
	+	5	7
	+	7	1
	+	5	7

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab09\poly.c
	*	1651676166	0
	"	21	14
	^	20	62
	.	20	61
	+	35	19
	+	35	16
	+	35	51
	+	35	53
	+	14	0
	+	27	39
	+	40	40
	+	51	82
	+	43	38
	+	56	38
	+	35	9
	+	32	18
	+	35	0
	+	32	0
	+	35	0
	+	47	0
	+	48	0
	+	45	0
	+	47	0
	+	45	0
	+	35	15
	+	35	13
	+	35	24
	+	35	12
	+	35	17
	+	35	26
	+	35	0
	+	35	13
	+	35	26
	+	35	21
	+	35	19
	+	35	0
	+	35	13
	+	35	0
	+	35	4
	+	35	31
	+	35	8
	+	35	18
	+	35	0
	+	35	22
	+	35	57
	+	35	19
	+	35	18
	+	35	17
	+	35	11
	+	35	15
	+	35	18
	+	35	17
	+	35	64
	+	35	0
	+	35	15
	+	15	14
	+	27	21
	+	15	15
	+	25	0
	+	26	0
	+	35	0
	+	17	0
	+	25	0
	+	35	0
	+	33	28
	+	15	54
	+	22	22
	+	30	0
	+	29	39
	+	30	0
	+	17	0
	+	33	19
	+	22	21
	+	22	23
	+	22	17
	+	22	18
	+	22	16
	+	18	27
	+	22	23
	+	18	32
	+	17	29
	+	22	2
	+	22	0
	+	33	0
	+	51	0
	+	15	3
	+	25	0
	+	22	0
	+	20	0
	+	33	32
	+	34	15
	+	22	0
	+	23	0
	+	20	30
	+	33	5
	+	19	23
	+	20	9
	+	23	23
	+	20	21
	+	24	12
	+	20	0
	+	7	0
	+	29	49
	+	20	61

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab09\poly.h
	*	1651674804	0
	"	1	0
	^	10	49
	.	38	82
	+	13	0
	+	15	5
	+	20	0
	+	15	11
	+	39	0
	+	20	4
	+	15	2
	+	12	0
	+	15	1
	+	20	70
	+	26	7
	+	1	14
	+	2	6
	+	40	5
	+	7	19
	+	8	0
	+	26	3
	+	31	3
	+	38	39
	+	14	0
	+	4	0
	+	3	0
	+	6	0
	+	14	19
	+	17	3
	+	18	65
	+	19	2
	+	23	78
	+	25	2
	+	29	33
	+	30	2
	+	34	0
	+	38	0
	+	34	3
	+	37	2
	+	34	79
	+	35	52
	+	36	78
	+	10	39
	+	11	2
	+	10	48
	+	26	39
	+	31	40
	+	38	82

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab09\main.c
	*	1651674672	0
	"	32	0
	^	75	0
	.	75	0
	+	1	0
	+	75	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\RGB.vhd
	*	1651613361	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\ov7670_registers.vhd
	*	1651613348	0
	"	33	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\ov7670_controller.vhd
	*	1651613305	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\vga.vhd
	*	1651613243	0
	"	62	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Embedded_3\Lab\CamTemp\fpgaCamera\Library\Address_Generator.vhd
	*	1651613187	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\SCP_FPGA\SCP_FPGA.qpf
	*	1651596381	0
	"	30	27
	^	30	28
	.	30	27
	+	30	27

> ~\IdeaProjects\SoftDevII\mitchellLab08\src\mitchell\ImageIO.java
	*	1651521251	0
	"	101	35

> ~\IdeaProjects\SoftDevII\mitchellLab08\src\mitchell\ImageEditorController.java
	*	1651516735	0
	"	46	12

> C:\intelFPGA_lite\18.1\University_Program\Computer_Systems\DE10-Lite\DE10-CE2820\verilog\servo.vhd
	*	1651359416	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\Rotator\Rotator.vhd
	*	1651359305	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\Regfile\Regfile.vhd
	*	1651354679	0
	"	173	5
	^	294	0
	.	172	0
	+	308	0
	+	307	0
	+	308	0
	+	289	0
	+	302	0
	+	309	0
	+	171	0
	+	172	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\IROM\IROM.vhd
	*	1651354567	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\Extender\Extender.vhd
	*	1651354538	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Computer_Architecture\VHDL\ALU\ALU.vhd
	*	1651354509	0
	"	11	0

> ~\IdeaProjects\DataStructures\lab7-jones-mitchell-johnstone\src\johnstonem\MorseDecoder.java
	*	1651250697	0
	"	68	0

> ~\IdeaProjects\DataStructures\lab7-jones-mitchell-johnstone\src\johnstonem\MorseTree.java
	*	1651250680	0
	"	79	8
	.	77	0
	+	77	0

> C:\CompProg\CinCity\Mitchell\test.cpp
	*	1651242846	0
	"	47	8
	^	47	14
	.	47	8
	+	113	0
	+	63	0
	+	1	0
	+	49	28
	+	38	11
	+	45	0
	+	52	0
	+	56	4
	+	62	1
	+	63	0
	+	61	9
	+	60	37
	+	59	37
	+	58	37
	+	57	32
	+	56	0
	+	50	10
	+	45	0
	+	48	17
	+	47	8

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Homework\HW8\hw8.cpp
	*	1651082066	0
	"	102	0
	^	92	7
	.	92	6
	+	1	22
	+	28	56
	+	56	3
	+	2	0
	+	9	0
	+	11	0
	+	15	0
	+	19	0
	+	22	0
	+	26	0
	+	28	0
	+	46	0
	+	48	0
	+	51	0
	+	54	0
	+	29	20
	+	31	0
	+	35	0
	+	40	0
	+	56	0
	+	57	0
	+	58	54
	+	58	0
	+	59	0
	+	62	0
	+	63	0
	+	66	0
	+	70	0
	+	74	0
	+	80	0
	+	82	0
	+	77	0
	+	86	0
	+	95	0
	+	93	0
	+	90	0
	+	89	0
	+	90	0
	+	91	0
	+	99	0
	+	14	16
	+	45	16
	+	46	31
	+	32	5
	+	34	4
	+	36	5
	+	39	4
	+	91	6
	+	92	6

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\ed.cpp
	*	1651077353	0
	"	154	4
	^	52	2
	.	65	0
	+	55	6
	+	55	0
	+	57	12
	+	55	0
	+	52	0
	+	57	0
	+	65	1
	+	52	0
	+	65	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\doc.cpp
	*	1651077238	0
	"	116	8
	^	113	29
	.	116	0
	+	100	34
	+	103	0
	+	101	15
	+	66	29
	+	54	32
	+	91	82
	+	91	0
	+	91	67
	+	35	5
	+	35	7
	+	35	0
	+	39	0
	+	40	0
	+	36	0
	+	100	0
	+	99	34
	+	100	20
	+	99	39
	+	13	17
	+	91	22
	+	66	0
	+	91	40
	+	91	42
	+	91	14
	+	91	52
	+	91	0
	+	91	20
	+	91	36
	+	9	16
	+	24	0
	+	24	10
	+	9	14
	+	91	19
	+	91	17
	+	91	26
	+	91	22
	+	91	0
	+	91	26
	+	91	0
	+	91	41
	+	91	33
	+	91	41
	+	91	26
	+	24	0
	+	60	34
	+	66	32
	+	91	0
	+	14	0
	+	60	0
	+	54	0
	+	91	1
	+	91	0
	+	60	0
	+	54	0
	+	60	44
	+	59	0
	+	54	0
	+	59	21
	+	55	32
	+	60	65
	+	66	61
	+	91	44
	+	60	0
	+	100	27
	+	91	69
	+	9	0
	+	91	0
	+	90	0
	+	91	0
	+	73	0
	+	90	0
	+	71	20
	+	66	0
	+	66	7
	+	71	7
	+	73	0
	+	90	0
	+	66	0
	+	60	0
	+	54	0
	+	65	19
	+	66	0
	+	111	25
	+	112	0
	+	117	14
	+	117	34
	+	116	0
	+	113	26
	+	117	0
	+	115	11
	+	113	56
	+	115	0
	+	116	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\line.cpp
	*	1651076289	0
	"	18	4
	^	3	23
	.	18	0
	+	18	38
	+	27	23
	+	30	16
	+	31	0
	+	26	23
	+	19	0
	+	2	28
	+	4	0
	+	3	22
	+	25	0
	+	18	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\doc.c
	*	1651076270	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\doc.h
	*	1651076266	0
	"	59	0
	^	4	23
	.	4	22
	+	3	28
	+	4	22

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\t2
	*	1651076199	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\line.h
	*	1651076066	0
	"	33	5

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\words.h
	*	1651075951	0
	"	37	0
	^	37	2
	.	37	0
	+	42	0
	+	39	21
	+	36	14
	+	38	0
	+	37	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\object.h
	*	1651075944	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\word.h
	*	1651073693	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\t1
	*	1651073348	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\object.cpp
	*	1651065598	0
	"	3	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab8\makefile
	*	1651027963	0
	"	12	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\Intro_To_AI\Lab\Lab_Final\game-of-life\README.md
	*	1651002166	0
	"	4	21
	^	4	22
	.	4	22
	+	2	33
	+	3	19
	+	4	22

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\CMakeLists.txt
	*	1650946480	0
	"	26	0

> ~\IdeaProjects\DataStructures\lab6-jones-mitchell-johnstone\src\johnstonem\Tests.java
	*	1650930207	0
	"	52	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\compile.shcmd
	*	1650930061	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\player.cpp
	*	1650861516	0
	"	1	0
	.	1	0
	+	1	0

> ~\Downloads\Solution (1).kt
	*	1650831249	0
	"	25	0

> C:\CompProg\CinCity\Mitchell\CodeJam2022\1B\pressure.cpp
	*	1650824437	0
	"	85	44
	^	87	15
	.	87	14
	+	1	0
	+	54	14
	+	55	12
	+	57	24
	+	66	37
	+	69	0
	+	59	38
	+	69	0
	+	59	26
	+	69	0
	+	69	12
	+	61	15
	+	68	26
	+	66	18
	+	66	0
	+	63	38
	+	68	28
	+	71	22
	+	92	31
	+	65	46
	+	68	33
	+	50	0
	+	63	73
	+	69	0
	+	68	0
	+	105	0
	+	102	13
	+	80	22
	+	83	15
	+	78	26
	+	84	11
	+	78	31
	+	84	22
	+	85	0
	+	84	8
	+	85	60
	+	87	14
	i	68	28

> C:\CompProg\CinCity\Mitchell\CodeJam2022\1B\database.cpp
	*	1650821353	0
	"	54	7
	^	54	8
	.	54	8
	+	1	0
	+	57	0
	+	56	0
	+	51	11
	+	56	0
	+	55	0
	+	54	8

> ~\Downloads\Solution (3).cpp
	*	1650817715	0
	"	183	6

> ~\Downloads\Solution (2).cpp
	*	1650817606	0
	"	99	6

> ~\Downloads\Solution.kt
	*	1650817545	0
	"	31	0

> C:\CompProg\CinCity\Mitchell\CodeJam2022\1B\pancakes.cpp
	*	1650816790	0
	"	67	24
	.	67	24
	+	63	0
	+	67	24

> ~\vimfiles\templates\skeleton.cpp
	*	1650816302	0
	"	62	3
	^	62	4
	.	62	4
	+	65	0
	+	65	152
	+	65	0
	+	65	4
	+	65	59
	+	65	0
	+	65	14
	+	65	0
	+	65	46
	+	65	19
	+	65	0
	+	65	11
	+	65	0
	+	65	22
	+	65	2
	+	65	51
	+	65	0
	+	65	32
	+	65	0
	+	65	12
	+	65	0
	+	65	18
	+	65	0
	+	65	15
	+	65	7
	+	65	59
	+	65	52
	+	65	0
	+	65	52
	+	65	0
	+	65	31
	+	65	0
	+	65	23
	+	65	44
	+	65	47
	+	65	35
	+	65	0
	+	65	11
	+	65	27
	+	65	34
	+	65	41
	+	65	0
	+	65	19
	+	65	47
	+	65	0
	+	65	49
	+	65	0
	+	65	11
	+	65	30
	+	65	37
	+	65	45
	+	65	0
	+	65	41
	+	65	0
	+	65	11
	+	65	24
	+	65	31
	+	65	38
	+	65	14
	+	65	36
	+	65	41
	+	65	42
	+	65	0
	+	65	3
	+	1	0
	+	65	0
	+	52	12
	+	63	0
	+	57	0
	+	63	0
	+	62	0
	+	60	0
	+	59	0
	+	58	0
	+	57	4
	+	58	4
	+	59	4
	+	60	8
	+	62	4

> C:\CompProg\CinCity\Mitchell\MSOE_Comp_2022\cipher.cpp
	*	1650753546	0
	"	60	27
	^	60	29
	.	60	29
	+	1	0
	+	67	8
	+	58	38
	+	62	39
	+	67	0
	+	66	21
	+	62	20
	+	57	19
	+	54	21
	+	62	14
	+	63	18
	+	65	0
	+	63	19
	+	65	0
	+	64	25
	+	62	28
	+	59	0
	+	61	13
	+	59	0
	+	60	25
	+	62	0
	+	60	29

> C:\CompProg\CinCity\Mitchell\MSOE_Comp_2022\sliding.cpp
	*	1650752885	0
	"	95	0
	^	95	0
	.	95	0
	+	53	22
	+	65	26
	+	76	1
	+	81	0
	+	98	15
	+	97	20
	+	97	0
	+	97	16
	+	97	11
	+	109	0
	+	112	36
	+	112	27
	+	112	39
	+	97	0
	+	112	90
	+	112	0
	+	110	42
	+	111	26
	+	112	48
	+	84	8
	+	85	8
	+	104	17
	+	107	17
	+	110	28
	+	111	29
	+	84	21
	+	85	21
	+	118	12
	+	93	0
	+	118	23
	+	72	4
	+	71	0
	+	76	14
	+	76	12
	+	76	8
	+	73	6
	+	110	43
	+	111	44
	+	110	44
	+	111	22
	+	110	0
	+	109	19
	+	76	0
	+	73	0
	+	72	5
	+	118	0
	+	85	23
	+	84	24
	+	116	12
	+	118	0
	+	115	23
	+	120	0
	+	84	28
	+	85	0
	+	116	31
	+	117	31
	+	82	0
	+	79	26
	+	96	37
	+	95	0

> C:\CompProg\CinCity\Mitchell\MSOE_Comp_2022\rpn.cpp
	*	1650749614	0
	"	49	42
	^	66	43
	.	66	42
	+	68	0
	+	50	0
	+	68	4
	+	50	26
	+	68	0
	+	68	26
	+	68	34
	+	68	9
	+	68	0
	+	68	10
	+	68	0
	+	68	24
	+	68	0
	+	68	35
	+	68	0
	+	68	27
	+	68	0
	+	68	16
	+	68	14
	+	68	31
	+	68	19
	+	68	0
	+	85	0
	+	80	23
	+	81	0
	+	77	19
	+	80	22
	+	81	0
	+	50	23
	+	51	12
	+	50	21
	+	64	0
	+	62	51
	+	51	68
	+	62	52
	+	64	40
	+	67	0
	+	64	0
	+	65	40
	+	83	19
	+	65	41
	+	67	38
	+	51	7
	+	65	7
	+	67	7
	+	62	26
	+	51	43
	+	62	13
	+	64	19
	+	64	17
	+	62	35
	+	64	27
	+	78	15
	+	80	0
	+	79	11
	+	81	9
	+	82	0
	+	81	24
	+	79	11
	+	74	0
	+	72	0
	+	73	0
	+	62	20
	+	64	0
	+	62	8
	+	52	6
	+	62	19
	+	62	25
	+	62	0
	+	63	36
	+	64	18
	+	64	0
	+	65	0
	+	64	0
	+	62	0
	+	67	0
	+	52	6
	+	67	0
	+	64	0
	+	62	0
	+	53	27
	+	62	0
	+	61	0
	+	56	12
	+	54	24
	+	56	30
	+	61	0
	+	60	0
	+	55	21
	+	57	34
	+	58	20
	+	55	20
	+	58	39
	+	59	28
	+	63	26
	+	64	22
	+	52	8
	+	66	42

> C:\CompProg\CinCity\Mitchell\MSOE_Comp_2022\spaces.cpp
	*	1650744280	0
	"	81	23
	^	87	51
	.	87	49
	+	57	0
	+	73	15
	+	83	0
	+	83	19
	+	88	0
	+	88	27
	+	105	12
	+	50	0
	+	54	0
	+	53	12
	+	54	32
	+	100	21
	+	56	28
	+	62	0
	+	61	20
	+	77	23
	+	86	19
	+	85	27
	+	72	13
	+	83	14
	+	83	0
	+	75	47
	+	87	36
	+	88	0
	+	87	8
	+	88	8
	+	87	35
	+	88	0
	+	83	0
	+	75	55
	+	87	47
	+	90	67
	+	83	0
	+	79	28
	+	81	23
	+	83	0
	+	72	14
	+	75	0
	+	85	8
	+	90	8
	+	92	0
	+	80	27
	+	85	0
	+	84	13
	+	104	26
	+	59	41
	+	87	50
	+	84	14
	+	87	49

> C:\CompProg\CinCity\Mitchell\MSOE_Comp_2022\monkey.cpp
	*	1650737626	0
	"	59	12
	^	78	13
	.	59	12
	+	1	0
	+	63	20
	+	79	0
	+	61	0
	+	63	0
	+	66	21
	+	68	0
	+	63	13
	+	67	24
	+	68	0
	+	79	0
	+	73	17
	+	69	15
	+	76	0
	+	73	46
	+	75	37
	+	76	0
	+	78	12
	+	61	0
	+	51	31
	+	52	32
	+	61	0
	+	53	22
	+	53	30
	+	54	33
	+	61	0
	+	53	0
	+	55	0
	+	60	23
	+	55	6
	+	55	30
	+	57	10
	+	63	0
	+	71	0
	+	78	12
	+	55	0
	+	59	12

> C:\CompProg\CinCity\Mitchell\MSOE_Comp_2022\handshake.cpp
	*	1650736127	0
	"	70	3
	^	60	17
	.	60	0
	+	1	0
	+	70	0
	+	63	16
	+	52	20
	+	65	27
	+	69	21
	+	65	16
	+	67	9
	+	66	12
	+	52	6
	+	51	6
	+	63	10
	+	66	12
	+	62	0
	+	53	14
	+	63	8
	+	65	0
	+	66	0
	+	65	0
	+	63	0
	+	61	0
	+	58	19
	+	58	20
	+	60	11
	+	58	36
	+	59	43
	+	60	48
	+	61	0
	+	60	49
	+	61	21
	+	61	0
	+	58	0
	+	54	0
	+	57	0
	+	55	20
	+	57	24
	+	58	22
	+	59	24
	+	60	20
	+	54	14
	+	58	23
	+	61	0
	+	60	16
	+	61	0
	+	60	8
	+	60	0

> C:\CompProg\CinCity\Mitchell\MSOE_Comp_2022\test.cpp
	*	1650734172	0
	"	52	16
	^	52	17
	.	52	16
	+	66	0
	+	117	24
	+	1	0
	+	53	0
	+	52	16

> C:\Program Files\Vim\vim82\doc\intro.txt
	*	1650734150	0
	"	456	14

> ~\vimfiles\templates.vim
	*	1650733999	0
	"	6	0
	^	4	67
	.	4	66
	+	2	0
	+	1	0
	+	2	0
	+	4	66

> ~\_vimrc
	*	1650733987	0
	"	8	23
	^	8	24
	.	8	24
	+	2	1212
	+	2	1214
	+	2	1280
	+	2	1358
	+	2	1434
	+	2	1456
	+	2	1501
	+	2	1555
	+	2	1595
	+	2	1607
	+	2	1642
	+	2	1653
	+	2	1669
	+	2	1679
	+	2	1697
	+	2	1716
	+	2	1793
	+	2	1823
	+	2	1839
	+	2	1901
	+	2	1928
	+	2	2001
	+	2	2028
	+	2	2045
	+	2	2067
	+	2	2088
	+	2	2109
	+	2	2127
	+	2	2146
	+	2	2169
	+	2	2196
	+	2	2214
	+	2	2236
	+	2	2257
	+	2	2278
	+	2	2296
	+	2	2315
	+	2	2335
	+	2	2353
	+	2	2376
	+	2	2442
	+	2	2466
	+	2	2508
	+	2	2526
	+	2	2548
	+	2	2567
	+	2	2584
	+	2	2606
	+	2	2623
	+	2	2658
	+	2	2678
	+	2	2691
	+	2	2710
	+	2	2728
	+	2	2794
	+	2	2807
	+	2	2813
	+	2	0
	+	2	15
	+	56	1
	+	55	0
	+	56	0
	+	2	24
	+	47	14
	+	50	14
	+	50	0
	+	47	21
	+	48	8
	+	47	9
	+	48	13
	+	48	66
	+	48	22
	+	48	60
	+	47	15
	+	48	38
	+	48	0
	+	54	66
	+	48	22
	+	54	66
	+	48	38
	+	48	0
	+	54	66
	+	48	44
	+	58	3
	+	2	0
	+	19	0
	+	20	30
	+	21	0
	+	11	27
	+	2	0
	+	3	0
	+	1	30
	+	22	3
	+	5	0
	+	6	0
	+	4	16
	+	7	0
	+	9	0
	+	7	7
	+	8	24

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\map.cpp
	*	1650604066	0
	"	97	34
	^	97	35
	.	97	34
	+	39	0
	+	37	0
	+	30	0
	+	34	0
	+	33	27
	+	39	0
	+	6	0
	+	7	0
	+	10	0
	+	6	25
	+	7	30
	+	10	20
	+	11	0
	+	12	0
	+	13	0
	+	11	28
	+	8	0
	+	9	0
	+	8	24
	+	9	20
	+	12	21
	+	13	0
	+	67	0
	+	80	0
	+	77	0
	+	79	0
	+	78	16
	+	77	44
	+	79	39
	+	77	35
	+	26	17
	+	63	28
	+	64	28
	+	76	23
	+	81	0
	+	69	0
	+	90	0
	+	75	0
	+	76	0
	+	73	0
	+	75	0
	+	73	8
	+	75	48
	+	84	0
	+	90	0
	+	84	31
	+	86	21
	+	87	21
	+	88	38
	+	89	64
	+	91	0
	+	91	35
	+	91	61
	+	91	0
	+	107	0
	+	92	13
	+	91	0
	+	99	0
	+	93	0
	+	93	17
	+	95	10
	+	96	10
	+	97	29
	+	98	51
	+	83	0
	+	82	0
	+	88	44
	+	91	0
	+	98	26
	+	97	34

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\main.cpp
	*	1650603197	0
	"	85	4

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\objects\gameObject.h
	*	1650602993	0
	"	31	42
	^	9	22
	.	35	42
	+	22	31
	+	28	33
	+	35	40
	+	9	21
	+	35	42

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\gameObject.h
	*	1650602978	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\objects\elevator.h
	*	1650600429	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\objects\ballPit.cpp
	*	1650600210	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\objects\pit.h
	*	1650599775	0
	"	1	0

> ~\OneDrive - Milwaukee School of Engineering\Sophomore\Spring\C&C++\Labs\lab06_7\src\map.h
	*	1650598419	0
	"	47	0
	.	47	0
	+	47	22
	+	47	6
	+	47	24
	+	47	0

> ~\vimfiles\test.cpp
	*	1650595644	0
	"	1	0

> ~\vimfiles\plugin.vim
	*	1650595193	0
	"	6	0
	^	5	0
	.	5	0
	+	4	0
	+	4	49
	+	4	17
	+	4	0
	+	4	77
	+	4	0
	+	4	77
	+	4	0
	+	4	78
	+	4	0
	+	2	0
	+	11	0
	+	9	0
	+	10	9
	+	1	11
	+	2	39
	+	8	1
	+	5	0

> C:\CompProg\CinCity\Mitchell\t.cpp
	*	1650595066	0
	"	51	3
	.	51	0
	+	1	0
	+	52	15
	+	52	14
	+	71	0
	+	57	19
	+	55	19
	+	55	0
	+	59	12
	+	60	17
	+	63	15
	+	63	20
	+	63	13
	+	63	18
	+	63	13
	+	64	18
	+	67	13
	+	68	18
	+	63	0
	+	37	39
	+	37	0
	+	37	34
	+	37	11
	+	37	31
	+	37	16
	+	37	0
	+	37	134
	+	37	43
	+	37	0
	+	44	0
	+	38	7
	+	36	9
	+	52	0
	+	38	57
	+	40	17
	+	38	27
	+	38	55
	+	40	0
	+	39	0
	+	52	0
	+	52	19
	+	52	26
	+	44	0
	+	34	0
	+	35	0
	+	44	0
	+	49	0
	+	52	13
	+	52	0
	+	51	3
	+	51	7
	+	51	0
